# Generated by Django 6.0 on 2025-12-14 16:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(default=django.utils.timezone.now)),
                ('average_cycle_length', models.FloatField(help_text='Rata-rata panjang siklus')),
                ('cycle_variability', models.FloatField(help_text='Variasi antar siklus')),
                ('analysis_type', models.CharField(choices=[('normal', 'Normal'), ('irregular', 'Irregular'), ('short', 'Short Cycle'), ('long', 'Long Cycle')], default='normal', max_length=20)),
                ('message', models.TextField(help_text='Pesan analisis untuk user')),
                ('recommendations', models.JSONField(default=list, help_text='List rekomendasi')),
                ('potential_causes', models.JSONField(default=list, help_text='List kemungkinan penyebab')),
                ('cycles_analyzed', models.IntegerField(help_text='Jumlah siklus yang dianalisis')),
                ('confidence_level', models.CharField(default='low', help_text='Tingkat kepercayaan analisis', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cycle Analysis',
                'verbose_name_plural': 'Cycle Analyses',
                'db_table': 'cycle_analyses',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='FertilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_cycle_length', models.IntegerField(default=28, help_text='Rata-rata panjang siklus dalam hari')),
                ('average_period_length', models.IntegerField(default=5, help_text='Rata-rata lama menstruasi dalam hari')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fertility_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fertility Profile',
                'verbose_name_plural': 'Fertility Profiles',
                'db_table': 'fertility_profiles',
            },
        ),
        migrations.CreateModel(
            name='MenstrualCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Hari pertama menstruasi')),
                ('end_date', models.DateField(blank=True, help_text='Hari terakhir menstruasi', null=True)),
                ('cycle_length', models.IntegerField(blank=True, help_text='Panjang siklus (hari)', null=True)),
                ('period_length', models.IntegerField(blank=True, help_text='Lama menstruasi (hari)', null=True)),
                ('ovulation_date', models.DateField(blank=True, help_text='Prediksi hari ovulasi', null=True)),
                ('fertile_window_start', models.DateField(blank=True, help_text='Awal masa subur', null=True)),
                ('fertile_window_end', models.DateField(blank=True, help_text='Akhir masa subur', null=True)),
                ('next_period_date', models.DateField(blank=True, help_text='Prediksi menstruasi berikutnya', null=True)),
                ('is_current', models.BooleanField(default=True, help_text='Apakah ini siklus saat ini')),
                ('notes', models.TextField(blank=True, help_text='Catatan tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menstrual_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menstrual Cycle',
                'verbose_name_plural': 'Menstrual Cycles',
                'db_table': 'menstrual_cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Tanggal gejala dialami')),
                ('symptom_type', models.CharField(help_text='Jenis gejala (misal: cramps, headache)', max_length=50)),
                ('category', models.CharField(choices=[('physical', 'Physical'), ('mood', 'Mood'), ('flow', 'Flow'), ('other', 'Other')], default='physical', max_length=20)),
                ('severity', models.IntegerField(blank=True, help_text='Tingkat keparahan 1-10', null=True)),
                ('notes', models.TextField(blank=True, help_text='Catatan tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
                'db_table': 'symptoms',
                'ordering': ['-date'],
            },
        ),
    ]
